- name: Demonstrates use of list variable in a playbook
  hosts: all
  vars:
    - software_tools:
         - vim
         - tree
         - tmux
         - net-tools
  tasks:
    - name: Install the list of software tools in Ubuntu nodes
      when: ansible_distribution == "Ubuntu"
      apt: name="{{item}}" state=latest update_cache=yes
      with_list: "{{software_tools}}"

    - name: Install the list of software tools in CentOS nodes
      when: ansible_distribution == "CentOS"
      yum: name="{{item}}" state=latest 
      with_list: "{{software_tools}}"
