- name: Demonstrates use of the sequence loop
  hosts: localhost 
  tasks:
    - debug: msg="Iteration - {{item}}"
      with_sequence: start=1  end=100 format="%03d"

    - shell: "touch file{{item}}.txt"
      with_sequence: start=1  end=5 format="%03d"
    
