- name: Configure nginx web root folder in CentOS ansible node
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes

- name: Open port 80 on firewall in CentOS ansible node
  shell: firewall-cmd --zone=public --add-port=80/tcp --permanent && firewall-cmd --reload

- name: Create the custom web root folder in CentOS ansible node
  file: path=/var/html state=directory mode=2775

- name: Grant permission to custom  web root folder in CentOS ansible node
  shell: chcon -Rt httpd_sys_content_t /var/html
