- name: This play will install, configure and deploy custom web page into nginx web server 
  hosts: all 
  tasks:
    - include: install-nginx-{{ansible_distribution|lower}}.yml
    - include: configure-nginx-{{ansible_distribution|lower}}.yml
    - include: common-nginx-tasks.yml
