- name: Demonstrates changing ansible node passwords
  hosts: ubuntu 
  vars_files:
    - credentials.txt

  become: yes

  tasks:
   - name: Change ansible node passsword
     user:
       name: "{{ubuntu_username}}"
       password: "{{ubuntu_password}}"
       update_password: always
   

