- name: This playbook demonstrates reading credentials stored in an external variable file
  hosts: localhost

  vars_files:
     - credentials.txt

  tasks:
     - debug: msg="Username is {{username}} and Password is {{password}}"    
