- name: This play will ping ubuntu and centos ansible nodes
  hosts: all
  tasks:
   - name: Ping the ansible node
     ping: 

  # - name: Execute a shell command
   - shell: hostname 


- name: This is the second play
  hosts: ubuntu
  tasks:
   - name: Execute some shell command
     shell: ifconfig
     
